"""Add User

Revision ID: 5bbdf002777e
Revises: 00113d01eba5
Create Date: 2024-11-30 21:29:56.280630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bbdf002777e'
down_revision = '00113d01eba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_questions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_questions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=64), nullable=False),
    sa.Column('question_text', sa.VARCHAR(length=64), nullable=False),
    sa.Column('option_a', sa.VARCHAR(length=64), nullable=False),
    sa.Column('option_b', sa.VARCHAR(length=64), nullable=False),
    sa.Column('option_c', sa.VARCHAR(length=64), nullable=False),
    sa.Column('option_d', sa.VARCHAR(length=64), nullable=False),
    sa.Column('correct_option', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
